// megafunction wizard: %ROM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: mem_tank1.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 18.1.0 Build 625 09/12/2018 SJ Lite Edition
// ************************************************************


//Copyright (C) 2018  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details.


//altsyncram ADDRESS_ACLR_A="NONE" CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone V" ENABLE_RUNTIME_MOD="NO" INIT_FILE="tanque1.mif" NUMWORDS_A=1024 OPERATION_MODE="ROM" OUTDATA_ACLR_A="NONE" OUTDATA_REG_A="CLOCK0" WIDTH_A=24 WIDTH_BYTEENA_A=1 WIDTHAD_A=10 address_a clock0 q_a
//VERSION_BEGIN 18.1 cbx_altera_syncram_nd_impl 2018:09:12:13:04:09:SJ cbx_altsyncram 2018:09:12:13:04:09:SJ cbx_cycloneii 2018:09:12:13:04:09:SJ cbx_lpm_add_sub 2018:09:12:13:04:09:SJ cbx_lpm_compare 2018:09:12:13:04:09:SJ cbx_lpm_decode 2018:09:12:13:04:09:SJ cbx_lpm_mux 2018:09:12:13:04:09:SJ cbx_mgl 2018:09:12:14:15:07:SJ cbx_nadder 2018:09:12:13:04:09:SJ cbx_stratix 2018:09:12:13:04:09:SJ cbx_stratixii 2018:09:12:13:04:09:SJ cbx_stratixiii 2018:09:12:13:04:09:SJ cbx_stratixv 2018:09:12:13:04:09:SJ cbx_util_mgl 2018:09:12:13:04:09:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = M10K 3 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  mem_tank1_altsyncram
	( 
	address_a,
	clock0,
	q_a) /* synthesis synthesis_clearbox=1 */;
	input   [9:0]  address_a;
	input   clock0;
	output   [23:0]  q_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block1a_0portadataout;
	wire  [0:0]   wire_ram_block1a_1portadataout;
	wire  [0:0]   wire_ram_block1a_2portadataout;
	wire  [0:0]   wire_ram_block1a_3portadataout;
	wire  [0:0]   wire_ram_block1a_4portadataout;
	wire  [0:0]   wire_ram_block1a_5portadataout;
	wire  [0:0]   wire_ram_block1a_6portadataout;
	wire  [0:0]   wire_ram_block1a_7portadataout;
	wire  [0:0]   wire_ram_block1a_8portadataout;
	wire  [0:0]   wire_ram_block1a_9portadataout;
	wire  [0:0]   wire_ram_block1a_10portadataout;
	wire  [0:0]   wire_ram_block1a_11portadataout;
	wire  [0:0]   wire_ram_block1a_12portadataout;
	wire  [0:0]   wire_ram_block1a_13portadataout;
	wire  [0:0]   wire_ram_block1a_14portadataout;
	wire  [0:0]   wire_ram_block1a_15portadataout;
	wire  [0:0]   wire_ram_block1a_16portadataout;
	wire  [0:0]   wire_ram_block1a_17portadataout;
	wire  [0:0]   wire_ram_block1a_18portadataout;
	wire  [0:0]   wire_ram_block1a_19portadataout;
	wire  [0:0]   wire_ram_block1a_20portadataout;
	wire  [0:0]   wire_ram_block1a_21portadataout;
	wire  [0:0]   wire_ram_block1a_22portadataout;
	wire  [0:0]   wire_ram_block1a_23portadataout;
	wire  [9:0]  address_a_wire;

	cyclonev_ram_block   ram_block1a_0
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_0portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_0.clk0_core_clock_enable = "none",
		ram_block1a_0.clk0_input_clock_enable = "none",
		ram_block1a_0.clk0_output_clock_enable = "none",
		ram_block1a_0.connectivity_checking = "OFF",
		ram_block1a_0.init_file = "tanque1.mif",
		ram_block1a_0.init_file_layout = "port_a",
		ram_block1a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_0.mem_init0 = 1024'h00000000000000000000000000FFFF000080010000FFFF000FFFFFF00F7FFEF008FFFF100FFFFFF008FFFF100F7FFEF00FFFFFF00FFFFFF000FFFF00087FFE100FFFFFF00FFFFFF00F7FFEF00FFFFFF00FFFFFF0087FFE100F7FFEF0070180E00000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_0.operation_mode = "rom",
		ram_block1a_0.port_a_address_clear = "none",
		ram_block1a_0.port_a_address_width = 10,
		ram_block1a_0.port_a_data_out_clear = "none",
		ram_block1a_0.port_a_data_out_clock = "clock0",
		ram_block1a_0.port_a_data_width = 1,
		ram_block1a_0.port_a_first_address = 0,
		ram_block1a_0.port_a_first_bit_number = 0,
		ram_block1a_0.port_a_last_address = 1023,
		ram_block1a_0.port_a_logical_ram_depth = 1024,
		ram_block1a_0.port_a_logical_ram_width = 24,
		ram_block1a_0.ram_block_type = "AUTO",
		ram_block1a_0.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_1
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_1portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_1.clk0_core_clock_enable = "none",
		ram_block1a_1.clk0_input_clock_enable = "none",
		ram_block1a_1.clk0_output_clock_enable = "none",
		ram_block1a_1.connectivity_checking = "OFF",
		ram_block1a_1.init_file = "tanque1.mif",
		ram_block1a_1.init_file_layout = "port_a",
		ram_block1a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_1.mem_init0 = 1024'h000000000000000000000000000000000000000000FFFF00087FFE100F7FFEF00F7FFEF007FFFFE00FFFFFF00F7FFEF0087FFE1007FFFFE0077FFEE0077FFEE008FFFF10007FFE000F7FFEF0087FFE1007FFFFE0007FFE000F7FFEF0008241000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_1.operation_mode = "rom",
		ram_block1a_1.port_a_address_clear = "none",
		ram_block1a_1.port_a_address_width = 10,
		ram_block1a_1.port_a_data_out_clear = "none",
		ram_block1a_1.port_a_data_out_clock = "clock0",
		ram_block1a_1.port_a_data_width = 1,
		ram_block1a_1.port_a_first_address = 0,
		ram_block1a_1.port_a_first_bit_number = 1,
		ram_block1a_1.port_a_last_address = 1023,
		ram_block1a_1.port_a_logical_ram_depth = 1024,
		ram_block1a_1.port_a_logical_ram_width = 24,
		ram_block1a_1.ram_block_type = "AUTO",
		ram_block1a_1.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_2
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_2portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_2.clk0_core_clock_enable = "none",
		ram_block1a_2.clk0_input_clock_enable = "none",
		ram_block1a_2.clk0_output_clock_enable = "none",
		ram_block1a_2.connectivity_checking = "OFF",
		ram_block1a_2.init_file = "tanque1.mif",
		ram_block1a_2.init_file_layout = "port_a",
		ram_block1a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_2.mem_init0 = 1024'h00000000000000000000000000000000007FFE00007FFE00007FFE00007FFE000F7FFEF0007FFE0007FFFFE0007FFE0007FFFFE0007FFE0007FFFFE007FFFFE0087FFE1000FFFF00007FFE00077FFEE0007FFE0000FFFF00007FFE00087DBE100000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_2.operation_mode = "rom",
		ram_block1a_2.port_a_address_clear = "none",
		ram_block1a_2.port_a_address_width = 10,
		ram_block1a_2.port_a_data_out_clear = "none",
		ram_block1a_2.port_a_data_out_clock = "clock0",
		ram_block1a_2.port_a_data_width = 1,
		ram_block1a_2.port_a_first_address = 0,
		ram_block1a_2.port_a_first_bit_number = 2,
		ram_block1a_2.port_a_last_address = 1023,
		ram_block1a_2.port_a_logical_ram_depth = 1024,
		ram_block1a_2.port_a_logical_ram_width = 24,
		ram_block1a_2.ram_block_type = "AUTO",
		ram_block1a_2.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_3
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_3portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_3.clk0_core_clock_enable = "none",
		ram_block1a_3.clk0_input_clock_enable = "none",
		ram_block1a_3.clk0_output_clock_enable = "none",
		ram_block1a_3.connectivity_checking = "OFF",
		ram_block1a_3.init_file = "tanque1.mif",
		ram_block1a_3.init_file_layout = "port_a",
		ram_block1a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_3.mem_init0 = 1024'h000000000000000000000000007FFE00007FFE0000FFFF00077FFEE0087FFE1007FFFFE008FFFF10007FFE00087FFE10087FFE1008FFFF100FFFFFF00FFFFFF000FFFF000FFFFFF0087FFE10077FFEE008FFFF1007FFFFE0087FFE10078001E00000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_3.operation_mode = "rom",
		ram_block1a_3.port_a_address_clear = "none",
		ram_block1a_3.port_a_address_width = 10,
		ram_block1a_3.port_a_data_out_clear = "none",
		ram_block1a_3.port_a_data_out_clock = "clock0",
		ram_block1a_3.port_a_data_width = 1,
		ram_block1a_3.port_a_first_address = 0,
		ram_block1a_3.port_a_first_bit_number = 3,
		ram_block1a_3.port_a_last_address = 1023,
		ram_block1a_3.port_a_logical_ram_depth = 1024,
		ram_block1a_3.port_a_logical_ram_width = 24,
		ram_block1a_3.ram_block_type = "AUTO",
		ram_block1a_3.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_4
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_4portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_4.clk0_core_clock_enable = "none",
		ram_block1a_4.clk0_input_clock_enable = "none",
		ram_block1a_4.clk0_output_clock_enable = "none",
		ram_block1a_4.connectivity_checking = "OFF",
		ram_block1a_4.init_file = "tanque1.mif",
		ram_block1a_4.init_file_layout = "port_a",
		ram_block1a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_4.mem_init0 = 1024'h00000000000000000000000000FFFF0000FFFF0000FFFF0000FFFF00077FFEE0077FFEE00F7FFEF00F7FFEF0077FFEE00FFFFFF00F7FFEF000FFFF0000FFFF000F7FFEF0077FFEE0077FFEE000FFFF000F7FFEF00FFFFFF0077FFEE0008241000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_4.operation_mode = "rom",
		ram_block1a_4.port_a_address_clear = "none",
		ram_block1a_4.port_a_address_width = 10,
		ram_block1a_4.port_a_data_out_clear = "none",
		ram_block1a_4.port_a_data_out_clock = "clock0",
		ram_block1a_4.port_a_data_width = 1,
		ram_block1a_4.port_a_first_address = 0,
		ram_block1a_4.port_a_first_bit_number = 4,
		ram_block1a_4.port_a_last_address = 1023,
		ram_block1a_4.port_a_logical_ram_depth = 1024,
		ram_block1a_4.port_a_logical_ram_width = 24,
		ram_block1a_4.ram_block_type = "AUTO",
		ram_block1a_4.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_5
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_5portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_5.clk0_core_clock_enable = "none",
		ram_block1a_5.clk0_input_clock_enable = "none",
		ram_block1a_5.clk0_output_clock_enable = "none",
		ram_block1a_5.connectivity_checking = "OFF",
		ram_block1a_5.init_file = "tanque1.mif",
		ram_block1a_5.init_file_layout = "port_a",
		ram_block1a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_5.mem_init0 = 1024'h000000000000000000000000000000000080010000FFFF000F7FFEF00F7FFEF00FFFFFF0077FFEE00F7FFEF00F7FFEF008FFFF10077FFEE00FFFFFF00FFFFFF0077FFEE00FFFFFF00F7FFEF0007FFE00077FFEE0007FFE000F7FFEF00F83C1F00000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_5.operation_mode = "rom",
		ram_block1a_5.port_a_address_clear = "none",
		ram_block1a_5.port_a_address_width = 10,
		ram_block1a_5.port_a_data_out_clear = "none",
		ram_block1a_5.port_a_data_out_clock = "clock0",
		ram_block1a_5.port_a_data_width = 1,
		ram_block1a_5.port_a_first_address = 0,
		ram_block1a_5.port_a_first_bit_number = 5,
		ram_block1a_5.port_a_last_address = 1023,
		ram_block1a_5.port_a_logical_ram_depth = 1024,
		ram_block1a_5.port_a_logical_ram_width = 24,
		ram_block1a_5.ram_block_type = "AUTO",
		ram_block1a_5.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_6
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_6portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_6.clk0_core_clock_enable = "none",
		ram_block1a_6.clk0_input_clock_enable = "none",
		ram_block1a_6.clk0_output_clock_enable = "none",
		ram_block1a_6.connectivity_checking = "OFF",
		ram_block1a_6.init_file = "tanque1.mif",
		ram_block1a_6.init_file_layout = "port_a",
		ram_block1a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_6.mem_init0 = 1024'h0000000000000000000000000000000000FFFF0000FFFF0000FFFF0000FFFF000FFFFFF0007FFE0000FFFF0000FFFF0008FFFF10007FFE00007FFE00007FFE00007FFE000FFFFFF000FFFF000FFFFFF0007FFE000FFFFFF000FFFF000003C0000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_6.operation_mode = "rom",
		ram_block1a_6.port_a_address_clear = "none",
		ram_block1a_6.port_a_address_width = 10,
		ram_block1a_6.port_a_data_out_clear = "none",
		ram_block1a_6.port_a_data_out_clock = "clock0",
		ram_block1a_6.port_a_data_width = 1,
		ram_block1a_6.port_a_first_address = 0,
		ram_block1a_6.port_a_first_bit_number = 6,
		ram_block1a_6.port_a_last_address = 1023,
		ram_block1a_6.port_a_logical_ram_depth = 1024,
		ram_block1a_6.port_a_logical_ram_width = 24,
		ram_block1a_6.ram_block_type = "AUTO",
		ram_block1a_6.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_7
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_7portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_7.clk0_core_clock_enable = "none",
		ram_block1a_7.clk0_input_clock_enable = "none",
		ram_block1a_7.clk0_output_clock_enable = "none",
		ram_block1a_7.connectivity_checking = "OFF",
		ram_block1a_7.init_file = "tanque1.mif",
		ram_block1a_7.init_file_layout = "port_a",
		ram_block1a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_7.mem_init0 = 1024'h00000000000000000000000000000000007FFE00007FFE00007FFE00007FFE00007FFE000FFFFFF0007FFE00007FFE00077FFEE00FFFFFF0007FFE00007FFE000FFFFFF0007FFE00007FFE00007FFE000FFFFFF0007FFE00007FFE00007C3E000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_7.operation_mode = "rom",
		ram_block1a_7.port_a_address_clear = "none",
		ram_block1a_7.port_a_address_width = 10,
		ram_block1a_7.port_a_data_out_clear = "none",
		ram_block1a_7.port_a_data_out_clock = "clock0",
		ram_block1a_7.port_a_data_width = 1,
		ram_block1a_7.port_a_first_address = 0,
		ram_block1a_7.port_a_first_bit_number = 7,
		ram_block1a_7.port_a_last_address = 1023,
		ram_block1a_7.port_a_logical_ram_depth = 1024,
		ram_block1a_7.port_a_logical_ram_width = 24,
		ram_block1a_7.ram_block_type = "AUTO",
		ram_block1a_7.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_8
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_8portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_8.clk0_core_clock_enable = "none",
		ram_block1a_8.clk0_input_clock_enable = "none",
		ram_block1a_8.clk0_output_clock_enable = "none",
		ram_block1a_8.connectivity_checking = "OFF",
		ram_block1a_8.init_file = "tanque1.mif",
		ram_block1a_8.init_file_layout = "port_a",
		ram_block1a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_8.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000F0000F00F0000F0080000100F8001F0080000100F0000F00F0000F00F8001F000800100080000100F8001F00F0000F00F0000F00F8001F00F8001F0088001100F0000F0070000E00000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_8.operation_mode = "rom",
		ram_block1a_8.port_a_address_clear = "none",
		ram_block1a_8.port_a_address_width = 10,
		ram_block1a_8.port_a_data_out_clear = "none",
		ram_block1a_8.port_a_data_out_clock = "clock0",
		ram_block1a_8.port_a_data_width = 1,
		ram_block1a_8.port_a_first_address = 0,
		ram_block1a_8.port_a_first_bit_number = 8,
		ram_block1a_8.port_a_last_address = 1023,
		ram_block1a_8.port_a_logical_ram_depth = 1024,
		ram_block1a_8.port_a_logical_ram_width = 24,
		ram_block1a_8.ram_block_type = "AUTO",
		ram_block1a_8.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_9
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_9portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_9.clk0_core_clock_enable = "none",
		ram_block1a_9.clk0_input_clock_enable = "none",
		ram_block1a_9.clk0_output_clock_enable = "none",
		ram_block1a_9.connectivity_checking = "OFF",
		ram_block1a_9.init_file = "tanque1.mif",
		ram_block1a_9.init_file_layout = "port_a",
		ram_block1a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_9.mem_init0 = 1024'h000000000000000000000000000000000000000000000000080000100F8001F00F8001F0070000E00F0000F00F8001F008000010070000E0070000E0070000E008000010000000000F8001F008000010070000E0000000000F8001F0000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_9.operation_mode = "rom",
		ram_block1a_9.port_a_address_clear = "none",
		ram_block1a_9.port_a_address_width = 10,
		ram_block1a_9.port_a_data_out_clear = "none",
		ram_block1a_9.port_a_data_out_clock = "clock0",
		ram_block1a_9.port_a_data_width = 1,
		ram_block1a_9.port_a_first_address = 0,
		ram_block1a_9.port_a_first_bit_number = 9,
		ram_block1a_9.port_a_last_address = 1023,
		ram_block1a_9.port_a_logical_ram_depth = 1024,
		ram_block1a_9.port_a_logical_ram_width = 24,
		ram_block1a_9.ram_block_type = "AUTO",
		ram_block1a_9.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_10
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_10portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_10.clk0_core_clock_enable = "none",
		ram_block1a_10.clk0_input_clock_enable = "none",
		ram_block1a_10.clk0_output_clock_enable = "none",
		ram_block1a_10.connectivity_checking = "OFF",
		ram_block1a_10.init_file = "tanque1.mif",
		ram_block1a_10.init_file_layout = "port_a",
		ram_block1a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_10.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000008001000F8001F000000000078001E000800100078001E000000000078001E0078001E0080000100080010000800100078001E0000000000000000000800100088001100000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_10.operation_mode = "rom",
		ram_block1a_10.port_a_address_clear = "none",
		ram_block1a_10.port_a_address_width = 10,
		ram_block1a_10.port_a_data_out_clear = "none",
		ram_block1a_10.port_a_data_out_clock = "clock0",
		ram_block1a_10.port_a_data_width = 1,
		ram_block1a_10.port_a_first_address = 0,
		ram_block1a_10.port_a_first_bit_number = 10,
		ram_block1a_10.port_a_last_address = 1023,
		ram_block1a_10.port_a_logical_ram_depth = 1024,
		ram_block1a_10.port_a_logical_ram_width = 24,
		ram_block1a_10.ram_block_type = "AUTO",
		ram_block1a_10.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_11
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_11portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_11.clk0_core_clock_enable = "none",
		ram_block1a_11.clk0_input_clock_enable = "none",
		ram_block1a_11.clk0_output_clock_enable = "none",
		ram_block1a_11.connectivity_checking = "OFF",
		ram_block1a_11.init_file = "tanque1.mif",
		ram_block1a_11.init_file_layout = "port_a",
		ram_block1a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_11.mem_init0 = 1024'h000000000000000000000000000000000000000000000000070000E008800110070000E008800110000000000880011008000010088001100F8001F00F8001F0008001000F8001F008800110078001E008800110078001E008800110070000E00000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_11.operation_mode = "rom",
		ram_block1a_11.port_a_address_clear = "none",
		ram_block1a_11.port_a_address_width = 10,
		ram_block1a_11.port_a_data_out_clear = "none",
		ram_block1a_11.port_a_data_out_clock = "clock0",
		ram_block1a_11.port_a_data_width = 1,
		ram_block1a_11.port_a_first_address = 0,
		ram_block1a_11.port_a_first_bit_number = 11,
		ram_block1a_11.port_a_last_address = 1023,
		ram_block1a_11.port_a_logical_ram_depth = 1024,
		ram_block1a_11.port_a_logical_ram_width = 24,
		ram_block1a_11.ram_block_type = "AUTO",
		ram_block1a_11.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_12
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_12portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_12.clk0_core_clock_enable = "none",
		ram_block1a_12.clk0_input_clock_enable = "none",
		ram_block1a_12.clk0_output_clock_enable = "none",
		ram_block1a_12.connectivity_checking = "OFF",
		ram_block1a_12.init_file = "tanque1.mif",
		ram_block1a_12.init_file_layout = "port_a",
		ram_block1a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_12.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000800100078001E0070000E00F0000F00F0000F0078001E00F8001F00F0000F000800100008001000F0000F0070000E0078001E0000000000F0000F00F8001F0078001E0008001000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_12.operation_mode = "rom",
		ram_block1a_12.port_a_address_clear = "none",
		ram_block1a_12.port_a_address_width = 10,
		ram_block1a_12.port_a_data_out_clear = "none",
		ram_block1a_12.port_a_data_out_clock = "clock0",
		ram_block1a_12.port_a_data_width = 1,
		ram_block1a_12.port_a_first_address = 0,
		ram_block1a_12.port_a_first_bit_number = 12,
		ram_block1a_12.port_a_last_address = 1023,
		ram_block1a_12.port_a_logical_ram_depth = 1024,
		ram_block1a_12.port_a_logical_ram_width = 24,
		ram_block1a_12.ram_block_type = "AUTO",
		ram_block1a_12.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_13
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_13portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_13.clk0_core_clock_enable = "none",
		ram_block1a_13.clk0_input_clock_enable = "none",
		ram_block1a_13.clk0_output_clock_enable = "none",
		ram_block1a_13.connectivity_checking = "OFF",
		ram_block1a_13.init_file = "tanque1.mif",
		ram_block1a_13.init_file_layout = "port_a",
		ram_block1a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_13.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000F0000F00F0000F00F0000F0078001E00F8001F00F0000F008000010078001E00F0000F00F0000F0078001E00F0000F00F0000F000800100078001E0008001000F0000F00F0000F00000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_13.operation_mode = "rom",
		ram_block1a_13.port_a_address_clear = "none",
		ram_block1a_13.port_a_address_width = 10,
		ram_block1a_13.port_a_data_out_clear = "none",
		ram_block1a_13.port_a_data_out_clock = "clock0",
		ram_block1a_13.port_a_data_width = 1,
		ram_block1a_13.port_a_first_address = 0,
		ram_block1a_13.port_a_first_bit_number = 13,
		ram_block1a_13.port_a_last_address = 1023,
		ram_block1a_13.port_a_logical_ram_depth = 1024,
		ram_block1a_13.port_a_logical_ram_width = 24,
		ram_block1a_13.ram_block_type = "AUTO",
		ram_block1a_13.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_14
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_14portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_14.clk0_core_clock_enable = "none",
		ram_block1a_14.clk0_input_clock_enable = "none",
		ram_block1a_14.clk0_output_clock_enable = "none",
		ram_block1a_14.connectivity_checking = "OFF",
		ram_block1a_14.init_file = "tanque1.mif",
		ram_block1a_14.init_file_layout = "port_a",
		ram_block1a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_14.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000000000F8001F000800100000000000000000008800110008001000000000000000000008001000F8001F0000000000F0000F0008001000F0000F000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_14.operation_mode = "rom",
		ram_block1a_14.port_a_address_clear = "none",
		ram_block1a_14.port_a_address_width = 10,
		ram_block1a_14.port_a_data_out_clear = "none",
		ram_block1a_14.port_a_data_out_clock = "clock0",
		ram_block1a_14.port_a_data_width = 1,
		ram_block1a_14.port_a_first_address = 0,
		ram_block1a_14.port_a_first_bit_number = 14,
		ram_block1a_14.port_a_last_address = 1023,
		ram_block1a_14.port_a_logical_ram_depth = 1024,
		ram_block1a_14.port_a_logical_ram_width = 24,
		ram_block1a_14.ram_block_type = "AUTO",
		ram_block1a_14.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_15
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_15portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_15.clk0_core_clock_enable = "none",
		ram_block1a_15.clk0_input_clock_enable = "none",
		ram_block1a_15.clk0_output_clock_enable = "none",
		ram_block1a_15.connectivity_checking = "OFF",
		ram_block1a_15.init_file = "tanque1.mif",
		ram_block1a_15.init_file_layout = "port_a",
		ram_block1a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_15.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000F0000F00000000000000000070000E00F0000F000000000000000000F0000F00000000000000000000000000F0000F00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_15.operation_mode = "rom",
		ram_block1a_15.port_a_address_clear = "none",
		ram_block1a_15.port_a_address_width = 10,
		ram_block1a_15.port_a_data_out_clear = "none",
		ram_block1a_15.port_a_data_out_clock = "clock0",
		ram_block1a_15.port_a_data_width = 1,
		ram_block1a_15.port_a_first_address = 0,
		ram_block1a_15.port_a_first_bit_number = 15,
		ram_block1a_15.port_a_last_address = 1023,
		ram_block1a_15.port_a_logical_ram_depth = 1024,
		ram_block1a_15.port_a_logical_ram_width = 24,
		ram_block1a_15.ram_block_type = "AUTO",
		ram_block1a_15.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_16
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_16portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_16.clk0_core_clock_enable = "none",
		ram_block1a_16.clk0_input_clock_enable = "none",
		ram_block1a_16.clk0_output_clock_enable = "none",
		ram_block1a_16.connectivity_checking = "OFF",
		ram_block1a_16.init_file = "tanque1.mif",
		ram_block1a_16.init_file_layout = "port_a",
		ram_block1a_16.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_16.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000F0000F00F0000F0080000100F8001F0080000100F0000F00F0000F00F8001F000800100080000100F8001F00F0000F00F0000F00F8001F00F8001F0088001100F0000F0070240E00001800000018000000180000000000000024000000000000000000000000000,
		ram_block1a_16.operation_mode = "rom",
		ram_block1a_16.port_a_address_clear = "none",
		ram_block1a_16.port_a_address_width = 10,
		ram_block1a_16.port_a_data_out_clear = "none",
		ram_block1a_16.port_a_data_out_clock = "clock0",
		ram_block1a_16.port_a_data_width = 1,
		ram_block1a_16.port_a_first_address = 0,
		ram_block1a_16.port_a_first_bit_number = 16,
		ram_block1a_16.port_a_last_address = 1023,
		ram_block1a_16.port_a_logical_ram_depth = 1024,
		ram_block1a_16.port_a_logical_ram_width = 24,
		ram_block1a_16.ram_block_type = "AUTO",
		ram_block1a_16.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_17
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_17portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_17.clk0_core_clock_enable = "none",
		ram_block1a_17.clk0_input_clock_enable = "none",
		ram_block1a_17.clk0_output_clock_enable = "none",
		ram_block1a_17.connectivity_checking = "OFF",
		ram_block1a_17.init_file = "tanque1.mif",
		ram_block1a_17.init_file_layout = "port_a",
		ram_block1a_17.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_17.mem_init0 = 1024'h000000000000000000000000000000000000000000000000080000100F8001F00F8001F0070000E00F0000F00F8001F008000010070000E0070000E0070000E008000010000000000F8001F008000010070000E0000000000F8001F0000180000003C0000003C0000003C0000000000000018000000000000000000000000000,
		ram_block1a_17.operation_mode = "rom",
		ram_block1a_17.port_a_address_clear = "none",
		ram_block1a_17.port_a_address_width = 10,
		ram_block1a_17.port_a_data_out_clear = "none",
		ram_block1a_17.port_a_data_out_clock = "clock0",
		ram_block1a_17.port_a_data_width = 1,
		ram_block1a_17.port_a_first_address = 0,
		ram_block1a_17.port_a_first_bit_number = 17,
		ram_block1a_17.port_a_last_address = 1023,
		ram_block1a_17.port_a_logical_ram_depth = 1024,
		ram_block1a_17.port_a_logical_ram_width = 24,
		ram_block1a_17.ram_block_type = "AUTO",
		ram_block1a_17.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_18
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_18portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_18.clk0_core_clock_enable = "none",
		ram_block1a_18.clk0_input_clock_enable = "none",
		ram_block1a_18.clk0_output_clock_enable = "none",
		ram_block1a_18.connectivity_checking = "OFF",
		ram_block1a_18.init_file = "tanque1.mif",
		ram_block1a_18.init_file_layout = "port_a",
		ram_block1a_18.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_18.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000008001000F8001F000000000078001E000800100078001E000000000078001E0078001E0080000100080010000800100078001E00000000000000000008001000883C110000180000001800000018000000180000003C000000000000000000000000000,
		ram_block1a_18.operation_mode = "rom",
		ram_block1a_18.port_a_address_clear = "none",
		ram_block1a_18.port_a_address_width = 10,
		ram_block1a_18.port_a_data_out_clear = "none",
		ram_block1a_18.port_a_data_out_clock = "clock0",
		ram_block1a_18.port_a_data_width = 1,
		ram_block1a_18.port_a_first_address = 0,
		ram_block1a_18.port_a_first_bit_number = 18,
		ram_block1a_18.port_a_last_address = 1023,
		ram_block1a_18.port_a_logical_ram_depth = 1024,
		ram_block1a_18.port_a_logical_ram_width = 24,
		ram_block1a_18.ram_block_type = "AUTO",
		ram_block1a_18.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_19
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_19portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_19.clk0_core_clock_enable = "none",
		ram_block1a_19.clk0_input_clock_enable = "none",
		ram_block1a_19.clk0_output_clock_enable = "none",
		ram_block1a_19.connectivity_checking = "OFF",
		ram_block1a_19.init_file = "tanque1.mif",
		ram_block1a_19.init_file_layout = "port_a",
		ram_block1a_19.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_19.mem_init0 = 1024'h000000000000000000000000000000000000000000000000070000E008800110070000E008800110000000000880011008000010088001100F8001F00F8001F0008001000F8001F008800110078001E008800110078001E008800110070240E00001800000018000000180000000000000018000000000000000000000000000,
		ram_block1a_19.operation_mode = "rom",
		ram_block1a_19.port_a_address_clear = "none",
		ram_block1a_19.port_a_address_width = 10,
		ram_block1a_19.port_a_data_out_clear = "none",
		ram_block1a_19.port_a_data_out_clock = "clock0",
		ram_block1a_19.port_a_data_width = 1,
		ram_block1a_19.port_a_first_address = 0,
		ram_block1a_19.port_a_first_bit_number = 19,
		ram_block1a_19.port_a_last_address = 1023,
		ram_block1a_19.port_a_logical_ram_depth = 1024,
		ram_block1a_19.port_a_logical_ram_width = 24,
		ram_block1a_19.ram_block_type = "AUTO",
		ram_block1a_19.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_20
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_20portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_20.clk0_core_clock_enable = "none",
		ram_block1a_20.clk0_input_clock_enable = "none",
		ram_block1a_20.clk0_output_clock_enable = "none",
		ram_block1a_20.connectivity_checking = "OFF",
		ram_block1a_20.init_file = "tanque1.mif",
		ram_block1a_20.init_file_layout = "port_a",
		ram_block1a_20.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_20.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000800100078001E0070000E00F0000F00F0000F0078001E00F8001F00F0000F000800100008001000F0000F0070000E0078001E0000000000F0000F00F8001F0078001E000800100000180000001800000018000000180000003C000000000000000000000000000,
		ram_block1a_20.operation_mode = "rom",
		ram_block1a_20.port_a_address_clear = "none",
		ram_block1a_20.port_a_address_width = 10,
		ram_block1a_20.port_a_data_out_clear = "none",
		ram_block1a_20.port_a_data_out_clock = "clock0",
		ram_block1a_20.port_a_data_width = 1,
		ram_block1a_20.port_a_first_address = 0,
		ram_block1a_20.port_a_first_bit_number = 20,
		ram_block1a_20.port_a_last_address = 1023,
		ram_block1a_20.port_a_logical_ram_depth = 1024,
		ram_block1a_20.port_a_logical_ram_width = 24,
		ram_block1a_20.ram_block_type = "AUTO",
		ram_block1a_20.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_21
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_21portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_21.clk0_core_clock_enable = "none",
		ram_block1a_21.clk0_input_clock_enable = "none",
		ram_block1a_21.clk0_output_clock_enable = "none",
		ram_block1a_21.connectivity_checking = "OFF",
		ram_block1a_21.init_file = "tanque1.mif",
		ram_block1a_21.init_file_layout = "port_a",
		ram_block1a_21.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_21.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000F0000F00F0000F00F0000F0078001E00F8001F00F0000F008000010078001E00F0000F00F0000F0078001E00F0000F00F0000F000800100078001E0008001000F0000F00F0180F0000180000001800000018000000180000003C000000000000000000000000000,
		ram_block1a_21.operation_mode = "rom",
		ram_block1a_21.port_a_address_clear = "none",
		ram_block1a_21.port_a_address_width = 10,
		ram_block1a_21.port_a_data_out_clear = "none",
		ram_block1a_21.port_a_data_out_clock = "clock0",
		ram_block1a_21.port_a_data_width = 1,
		ram_block1a_21.port_a_first_address = 0,
		ram_block1a_21.port_a_first_bit_number = 21,
		ram_block1a_21.port_a_last_address = 1023,
		ram_block1a_21.port_a_logical_ram_depth = 1024,
		ram_block1a_21.port_a_logical_ram_width = 24,
		ram_block1a_21.ram_block_type = "AUTO",
		ram_block1a_21.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_22
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_22portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_22.clk0_core_clock_enable = "none",
		ram_block1a_22.clk0_input_clock_enable = "none",
		ram_block1a_22.clk0_output_clock_enable = "none",
		ram_block1a_22.connectivity_checking = "OFF",
		ram_block1a_22.init_file = "tanque1.mif",
		ram_block1a_22.init_file_layout = "port_a",
		ram_block1a_22.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_22.mem_init0 = 1024'h00000000000000000000000000000000000000000000000000000000000000000F8001F000800100000000000000000008800110008001000000000000000000008001000F8001F0000000000F0000F0008001000F0000F000000000000000000001800000018000000180000001800000000000000000000000000000000000,
		ram_block1a_22.operation_mode = "rom",
		ram_block1a_22.port_a_address_clear = "none",
		ram_block1a_22.port_a_address_width = 10,
		ram_block1a_22.port_a_data_out_clear = "none",
		ram_block1a_22.port_a_data_out_clock = "clock0",
		ram_block1a_22.port_a_data_width = 1,
		ram_block1a_22.port_a_first_address = 0,
		ram_block1a_22.port_a_first_bit_number = 22,
		ram_block1a_22.port_a_last_address = 1023,
		ram_block1a_22.port_a_logical_ram_depth = 1024,
		ram_block1a_22.port_a_logical_ram_width = 24,
		ram_block1a_22.ram_block_type = "AUTO",
		ram_block1a_22.lpm_type = "cyclonev_ram_block";
	cyclonev_ram_block   ram_block1a_23
	( 
	.clk0(clock0),
	.dftout(),
	.eccstatus(),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_23portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1),
	.nerror(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_23.clk0_core_clock_enable = "none",
		ram_block1a_23.clk0_input_clock_enable = "none",
		ram_block1a_23.clk0_output_clock_enable = "none",
		ram_block1a_23.connectivity_checking = "OFF",
		ram_block1a_23.init_file = "tanque1.mif",
		ram_block1a_23.init_file_layout = "port_a",
		ram_block1a_23.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_23.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000F0000F00000000000000000070000E00F0000F000000000000000000F0000F00000000000000000000000000F0000F00000000000000000000000000003C0000003C0000003C0000003C00000000000000000000000000000000000,
		ram_block1a_23.operation_mode = "rom",
		ram_block1a_23.port_a_address_clear = "none",
		ram_block1a_23.port_a_address_width = 10,
		ram_block1a_23.port_a_data_out_clear = "none",
		ram_block1a_23.port_a_data_out_clock = "clock0",
		ram_block1a_23.port_a_data_width = 1,
		ram_block1a_23.port_a_first_address = 0,
		ram_block1a_23.port_a_first_bit_number = 23,
		ram_block1a_23.port_a_last_address = 1023,
		ram_block1a_23.port_a_logical_ram_depth = 1024,
		ram_block1a_23.port_a_logical_ram_width = 24,
		ram_block1a_23.ram_block_type = "AUTO",
		ram_block1a_23.lpm_type = "cyclonev_ram_block";
	assign
		address_a_wire = address_a,
		q_a = {wire_ram_block1a_23portadataout[0], wire_ram_block1a_22portadataout[0], wire_ram_block1a_21portadataout[0], wire_ram_block1a_20portadataout[0], wire_ram_block1a_19portadataout[0], wire_ram_block1a_18portadataout[0], wire_ram_block1a_17portadataout[0], wire_ram_block1a_16portadataout[0], wire_ram_block1a_15portadataout[0], wire_ram_block1a_14portadataout[0], wire_ram_block1a_13portadataout[0], wire_ram_block1a_12portadataout[0], wire_ram_block1a_11portadataout[0], wire_ram_block1a_10portadataout[0], wire_ram_block1a_9portadataout[0], wire_ram_block1a_8portadataout[0], wire_ram_block1a_7portadataout[0], wire_ram_block1a_6portadataout[0], wire_ram_block1a_5portadataout[0], wire_ram_block1a_4portadataout[0], wire_ram_block1a_3portadataout[0], wire_ram_block1a_2portadataout[0], wire_ram_block1a_1portadataout[0], wire_ram_block1a_0portadataout[0]};
endmodule //mem_tank1_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module mem_tank1 (
	address,
	clock,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	[9:0]  address;
	input	  clock;
	output	[23:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [23:0] sub_wire0;
	wire [23:0] q = sub_wire0[23:0];

	mem_tank1_altsyncram	mem_tank1_altsyncram_component (
				.address_a (address),
				.clock0 (clock),
				.q_a (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: AclrAddr NUMERIC "0"
// Retrieval info: PRIVATE: AclrByte NUMERIC "0"
// Retrieval info: PRIVATE: AclrOutput NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "8"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: Clken NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "tanque1.mif"
// Retrieval info: PRIVATE: NUMWORDS_A NUMERIC "1024"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: RegAddr NUMERIC "1"
// Retrieval info: PRIVATE: RegOutput NUMERIC "1"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SingleClock NUMERIC "1"
// Retrieval info: PRIVATE: UseDQRAM NUMERIC "0"
// Retrieval info: PRIVATE: WidthAddr NUMERIC "10"
// Retrieval info: PRIVATE: WidthData NUMERIC "24"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: ADDRESS_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: INIT_FILE STRING "tanque1.mif"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
// Retrieval info: CONSTANT: LPM_HINT STRING "ENABLE_RUNTIME_MOD=NO"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "1024"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "ROM"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "CLOCK0"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "10"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "24"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: address 0 0 10 0 INPUT NODEFVAL "address[9..0]"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC "clock"
// Retrieval info: USED_PORT: q 0 0 24 0 OUTPUT NODEFVAL "q[23..0]"
// Retrieval info: CONNECT: @address_a 0 0 10 0 address 0 0 10 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: q 0 0 24 0 @q_a 0 0 24 0
// Retrieval info: GEN_FILE: TYPE_NORMAL mem_tank1.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL mem_tank1.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL mem_tank1.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL mem_tank1.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL mem_tank1_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL mem_tank1_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL mem_tank1_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
